### ISSUE TITLE
UI - for the masses

### ISSUE THREAD

**Issue by KillSwitch422** [Groestlcoin/Groestlcoin-Easyminer#25]
While I am partial(I Like it) to the current colours and feel, 
I showed it to a few everyday people, and they were put off by the look.
The impression was that it looked like a geek only UI( this is not based on anything other than personal preference on there part but all 5 said similar things)

I assume that windows is so engrained in the "this is how it should look" that they wanted a familiar look and feel.
I showed them the UI for Awesome miner, and they seemed much more comfortable

Attached is screen from Awesome miner
![awesome miner](https://user-images.githubusercontent.com/34509332/34194778-07301bf8-e563-11e7-9015-ddead59d1c46.PNG)

While this would possibly be a pain to redo , and adds no real value as to output, it needs consideration in the long run if we want adoption by the everyday person(The People's Coin)

**Comment by aceoyame** [comment]
Having made the original here. I am kind if disappointed with the loss of focus. It was made to be something someone could open and it would just start mining directly into an electrum wallet with whatever it could with next to no setup.

From what I can see that awesome miner is not exactly like that and I see my original work here has drifted into being more of a mining front end/GUI rather than going for absolute minimalist

**Comment by KillSwitch422** [comment]
I agree the idea needs to be a simple as close to one click as possible, the thoughts here were just regarding the "Look". - It must not work like awesome miner that's not the point of the "easyminer" but I do think if its going to have a UI we should try have it look more "windows like" if we want mainstream adoption  the awesome miners was a example for look that pleased the other 5 ppl I showed only

For me there should be a setup on first run, after that you should never have to touch it again.

**Comment by Yokomoko** [comment]
Thanks for your feedback!

There is, effectively a setup screen on first run. This is where it tells you to install the wallet, detects your cards and tells you about the antivirus. 

I'm aiming to integrate a wallet directly into the Easyminer 2018 next year which will remove a big step of setting up the Electrum wallet. I'll also re-look into the design at this stage and maybe implement some kind of 'Theming' where people can specify the look that they want. 

In response to aceoyame:
I based this Easyminer on feedback on the Discord channel from the original Easyminer. I tried contacting you on a couple of occasions for your advice/thoughts on the new miner but never heard a response back.
- Electrum Wallet that came included was outdated, this put me off integrating it in the same way on the new miner. Additionally, even for me, it was confusing when opening up the original miner as it closes to set up the Electrum wallet without any indication it was doing so. I spent days thinking it wasn't working. As previously stated, a basic wallet will hopefully be included next year to remove this hurdle from the new miner.
- The miner sometimes looked like it was started, but the files miner had been removed from the Antivirus - Nothing in the logs on the UI to show this.
- URLs/Links would open in Notepad for a lot of people, this was a little odd.
- No certain way of knowing what hardware was being mined with, a lot of people were thinking they were mining with their graphics cards but it was actually mining with the CPU - At least on the new version you can specify what to use *IF* the 2 ways to detect the graphics cards fail.
- Difficult to judge if they are actually mining anything. I've added a link to Dwarfpool for easy access.

I spent about a month gathering feedback from the original and messaged you a few times with this feedback but heard nothing back.

**Comment by aceoyame** [comment]
Hi again,

I know people were trying to reach me. It was just that I recently lost my jib and couldn't give a shit right then and there.

The bugs that you were seeing are what happens in the span of two years with no one touching the code.

The reason I didn't say any thing really to what I've  seen is because I open sourced it so I was going to let the commonly do with my code as they please. I'm a big advocate of open source where possible. In this instance I wanted to let you all know I've been silently watching and offer some guidance that perhaps you are straying too far away from the original concept.

I admit, you seem to be a much better coder than I. Admittedly this was my first vb.net project and it was with me trying to use as much of my original vbscript to get it done. That said, good luck and please try to make it literally as few clicks ad possible to just "start mining". The rest are optional/advanced features and is why I stated as such initially at least back in my vbscript version (can't remember if .net version is the same). That was always my intention with this concept that in came up with starting with simplicity back in 2014.

**Comment by aceoyame** [comment]
I wish I could edit comments. I typed that whole last thing on my phone so sorry if it doesn't make sense or has typos
